services:
  redishort:
    build: .
    container_name: redishort
    restart: always
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: ["python", "main.py"]
